python3 train.py $@ \
   --githttp https://github.com/vadimkantorov/convasr/commit/%h \
   --verbose --lang ru \
   --model JasperNetBig \
   --train-batch-size 1024 --val-batch-size 1024 \
   --scheduler MultiStepLR --decay-milestones 120000 160000 \
   --lr 1e-2 \
   --optimizer NovoGrad \
   --train-data-path data/mixed_train.csv \
   --val-data-path data/mixed_val.csv data/clean_val.csv kontur_calls_micro/kontur_calls_micro.csv kontur_calls_micro/kontur_calls_micro.0.csv kontur_calls_micro/kontur_calls_micro.1.csv data/valset_by_rec22122019.0.csv data/valset_by_rec22122019.1.csv  data/valset_by_rec22122019.csv \
   --analyze kontur_calls_micro.csv \
   --val-iteration-interval 10000 \
   --fp16 O2 \
   --experiment-name long-train_bs1024 \
   --epochs 110 #\
